# Generated by Django 5.2.11 on 2026-02-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDailyRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('routines', models.JSONField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
