# Generated by Django 5.2.11 on 2026-02-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_globaldailyroutine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldailyroutine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
