# Generated by Django 5.2.11 on 2026-02-25 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_alter_globaldailyroutine_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='primary_color',
            field=models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingresa un color hexadecimal válido (ej: #FF5733)', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AddField(
            model_name='gym',
            name='secondary_color',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingresa un color hexadecimal válido (ej: #FF5733)', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='globaldailyroutine',
            name='routines',
            field=models.JSONField(default=dict),
        ),
    ]
