# Generated by Django 5.2.11 on 2026-02-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_gym_primary_color_gym_secondary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrs/'),
        ),
    ]
